// Autogenerated from Pigeon (v19.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class MNToken;

@interface MNToken : NSObject
+ (instancetype)makeWithAppName:(nullable NSString *)appName
    accessToken:(nullable NSString *)accessToken
    refreshToken:(nullable NSString *)refreshToken;
@property(nonatomic, copy, nullable) NSString * appName;
@property(nonatomic, copy, nullable) NSString * accessToken;
@property(nonatomic, copy, nullable) NSString * refreshToken;
@end

/// The codec used by MNFlutterAppApi.
NSObject<FlutterMessageCodec> *MNFlutterAppApiGetCodec(void);

@interface MNFlutterAppApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)displayAuthToken:(MNToken *)token completion:(void (^)(FlutterError *_Nullable))completion;
@end

/// The codec used by MNHostAppApi.
NSObject<FlutterMessageCodec> *MNHostAppApiGetCodec(void);

@protocol MNHostAppApi
- (void)cancelWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)finishAuthWithTokenToken:(MNToken *)token error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpMNHostAppApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MNHostAppApi> *_Nullable api);

extern void SetUpMNHostAppApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MNHostAppApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
