// Autogenerated from Pigeon (v20.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class --java_outToken;
@class --java_outHostInfo;

@interface --java_outToken : NSObject
+ (instancetype)makeWithAccessToken:(nullable NSString *)accessToken
    refreshToken:(nullable NSString *)refreshToken;
@property(nonatomic, copy, nullable) NSString * accessToken;
@property(nonatomic, copy, nullable) NSString * refreshToken;
@end

@interface --java_outHostInfo : NSObject
+ (instancetype)makeWithAppName:(nullable NSString *)appName
    locale:(nullable NSString *)locale;
@property(nonatomic, copy, nullable) NSString * appName;
@property(nonatomic, copy, nullable) NSString * locale;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *--java_outGetApiCodec(void);

@interface --java_outManiAuthApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)sendHostInfoHostInfo:(--java_outHostInfo *)hostInfo completion:(void (^)(FlutterError *_Nullable))completion;
@end


@protocol --java_outHostAppApi
- (void)cancelWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)finishAuthWithTokenToken:(--java_outToken *)token error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUp--java_outHostAppApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<--java_outHostAppApi> *_Nullable api);

extern void SetUp--java_outHostAppApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<--java_outHostAppApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
