// Autogenerated from Pigeon (v19.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "api.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface MNToken ()
+ (MNToken *)fromList:(NSArray *)list;
+ (nullable MNToken *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation MNToken
+ (instancetype)makeWithAppName:(nullable NSString *)appName
    accessToken:(nullable NSString *)accessToken
    refreshToken:(nullable NSString *)refreshToken {
  MNToken* pigeonResult = [[MNToken alloc] init];
  pigeonResult.appName = appName;
  pigeonResult.accessToken = accessToken;
  pigeonResult.refreshToken = refreshToken;
  return pigeonResult;
}
+ (MNToken *)fromList:(NSArray *)list {
  MNToken *pigeonResult = [[MNToken alloc] init];
  pigeonResult.appName = GetNullableObjectAtIndex(list, 0);
  pigeonResult.accessToken = GetNullableObjectAtIndex(list, 1);
  pigeonResult.refreshToken = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable MNToken *)nullableFromList:(NSArray *)list {
  return (list) ? [MNToken fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    self.appName ?: [NSNull null],
    self.accessToken ?: [NSNull null],
    self.refreshToken ?: [NSNull null],
  ];
}
@end

@interface MNFlutterAppApiCodecReader : FlutterStandardReader
@end
@implementation MNFlutterAppApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [MNToken fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface MNFlutterAppApiCodecWriter : FlutterStandardWriter
@end
@implementation MNFlutterAppApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[MNToken class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface MNFlutterAppApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation MNFlutterAppApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[MNFlutterAppApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[MNFlutterAppApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *MNFlutterAppApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    MNFlutterAppApiCodecReaderWriter *readerWriter = [[MNFlutterAppApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

@interface MNFlutterAppApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation MNFlutterAppApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)displayAuthToken:(MNToken *)arg_token completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.mani_auth.FlutterAppApi.displayAuth", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:MNFlutterAppApiGetCodec()];
  [channel sendMessage:@[arg_token ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

@interface MNHostAppApiCodecReader : FlutterStandardReader
@end
@implementation MNHostAppApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [MNToken fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface MNHostAppApiCodecWriter : FlutterStandardWriter
@end
@implementation MNHostAppApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[MNToken class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface MNHostAppApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation MNHostAppApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[MNHostAppApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[MNHostAppApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *MNHostAppApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    MNHostAppApiCodecReaderWriter *readerWriter = [[MNHostAppApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpMNHostAppApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MNHostAppApi> *api) {
  SetUpMNHostAppApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpMNHostAppApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MNHostAppApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.mani_auth.HostAppApi.cancel", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:MNHostAppApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(cancelWithError:)], @"MNHostAppApi api (%@) doesn't respond to @selector(cancelWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api cancelWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.mani_auth.HostAppApi.finishAuthWithToken", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:MNHostAppApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(finishAuthWithTokenToken:error:)], @"MNHostAppApi api (%@) doesn't respond to @selector(finishAuthWithTokenToken:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        MNToken *arg_token = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api finishAuthWithTokenToken:arg_token error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
